Repository mju-likelion/12th-hackathon-team2-server, pull requests merged in 2024-09, with the labels that each got.

#89 Feature/#86 스케쥴 어노테이션 적용
  src/main/java/com/example/mutsideout_mju/MutsideoutMjuApplication.java
  src/main/java/com/example/mutsideout_mju/service/RoomService.java
Labels: enhancement

#94 Feature/#90 중복 이름, 이메일 검증 로직 리팩터링
  src/main/java/com/example/mutsideout_mju/repository/UserRepository.java
  src/main/java/com/example/mutsideout_mju/service/AuthService.java
  src/main/java/com/example/mutsideout_mju/service/UserService.java
Labels: enhancement, refactor

#92 Feature/#87 감정일기, 실시간 집중세션 방 코드 리팩터링
  src/main/java/com/example/mutsideout_mju/dto/request/PaginationDto.java
  src/main/java/com/example/mutsideout_mju/entity/Diary.java
  src/main/java/com/example/mutsideout_mju/entity/Room.java
  src/main/java/com/example/mutsideout_mju/service/DiaryService.java
  src/main/java/com/example/mutsideout_mju/service/RoomService.java
Labels: refactor

#101 Feature/#100 TokenProvider 클래스 리팩토링
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationInterceptor.java
  src/main/java/com/example/mutsideout_mju/authentication/token/AccessTokenProvider.java
  src/main/java/com/example/mutsideout_mju/authentication/token/RefreshTokenProvider.java
  src/main/java/com/example/mutsideout_mju/service/AuthService.java
  src/main/java/com/example/mutsideout_mju/service/CookieService.java
Labels: refactor
