Repository mju-likelion/12th-hackathon-team2-server, pull requests merged in 2024-07, with the labels that each got.

#4 Feature/#1 spring initializing
  .gitignore
  .gitmessage.txt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/mutsideout_mju/MutsideoutMjuApplication.java
  src/test/java/com/example/mutsideout_mju/MutsideoutMjuApplicationTests.java
Labels: good first issue

#8 Feature/#2 엔티티 생성
  src/main/java/com/example/mutsideout_mju/entity/BaseEntity.java
  src/main/java/com/example/mutsideout_mju/entity/Diary.java
  src/main/java/com/example/mutsideout_mju/entity/Grade.java
  src/main/java/com/example/mutsideout_mju/entity/Planner.java
  src/main/java/com/example/mutsideout_mju/entity/Room.java
  src/main/java/com/example/mutsideout_mju/entity/Survey.java
  src/main/java/com/example/mutsideout_mju/entity/SurveyOption.java
  src/main/java/com/example/mutsideout_mju/entity/User.java
  src/main/java/com/example/mutsideout_mju/entity/UserSurvey.java
Labels: enhancement

#10 Feature/#9 공통 Response, Exception 생성
  src/main/java/com/example/mutsideout_mju/dto/response/ResponseDto.java
  src/main/java/com/example/mutsideout_mju/exception/BadRequestException.java
  src/main/java/com/example/mutsideout_mju/exception/ConflictException.java
  src/main/java/com/example/mutsideout_mju/exception/CustomException.java
  src/main/java/com/example/mutsideout_mju/exception/DtoValidationException.java
  src/main/java/com/example/mutsideout_mju/exception/ForbiddenException.java
  src/main/java/com/example/mutsideout_mju/exception/NotFoundException.java
  src/main/java/com/example/mutsideout_mju/exception/UnauthorizedException.java
  src/main/java/com/example/mutsideout_mju/exception/dto/ErrorResponseDto.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/exception/handler/ExceptionController.java
Labels: enhancement

#12 Feature/#11 로그인 검증된 유저 커스텀 어노테이션 생성
  build.gradle
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticatedUser.java
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticatedUserArgumentResolver.java
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationContext.java
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationExtractor.java
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationInterceptor.java
  src/main/java/com/example/mutsideout_mju/authentication/JwtEncoder.java
  src/main/java/com/example/mutsideout_mju/authentication/JwtTokenProvider.java
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/exception/UnauthorizedException.java
  src/main/java/com/example/mutsideout_mju/repository/UserRepository.java
Labels: enhancement

#16 Feature/#15 비밀번호 암호화 기능 추가
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationExtractor.java
  src/main/java/com/example/mutsideout_mju/authentication/AuthenticationInterceptor.java
  src/main/java/com/example/mutsideout_mju/authentication/PasswordHashEncryption.java
Labels: enhancement

#18 Feature/#17 회원가입 API 개발
  build.gradle
  src/main/java/com/example/mutsideout_mju/controller/AuthController.java
  src/main/java/com/example/mutsideout_mju/dto/request/auth/SignupDto.java
  src/main/java/com/example/mutsideout_mju/repository/UserRepository.java
  src/main/java/com/example/mutsideout_mju/service/AuthService.java
Labels: enhancement

#14 Feature/#7 Diary API 개발
  src/main/java/com/example/mutsideout_mju/controller/DiaryController.java
  src/main/java/com/example/mutsideout_mju/dto/request/PaginationDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/diary/UpdateDiaryDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/diary/WriteDiaryDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/PaginationData.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseDto.java
  src/main/java/com/example/mutsideout_mju/entity/Diary.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/DiaryRepository.java
  src/main/java/com/example/mutsideout_mju/service/DiaryService.java
Labels: enhancement

#13 Feature/#6 planner api 개발
  src/main/java/com/example/mutsideout_mju/controller/PlannerController.java
  src/main/java/com/example/mutsideout_mju/dto/request/planner/CompletePlannerRequestDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/planner/PlannerDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/CompletedPlannerListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/CompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/GroupedCompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/PlannerListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/PlannerResponseData.java
  src/main/java/com/example/mutsideout_mju/entity/Planner.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/PlannerRepository.java
  src/main/java/com/example/mutsideout_mju/service/PlannerService.java
Labels: enhancement

#24 Feature/#21 설문조사(ADHD 테스트) API 개발
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/controller/SurveyController.java
  src/main/java/com/example/mutsideout_mju/dto/request/survey/SurveyResult.java
  src/main/java/com/example/mutsideout_mju/dto/request/survey/SurveyResultListDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/survey/SurveyQuestionData.java
  src/main/java/com/example/mutsideout_mju/dto/response/survey/SurveyQuestionListResponseDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/user/UserGradeResponseDto.java
  src/main/java/com/example/mutsideout_mju/entity/User.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/SurveyRepository.java
  src/main/java/com/example/mutsideout_mju/repository/UserSurveyRepository.java
  src/main/java/com/example/mutsideout_mju/service/SurveyService.java
  src/main/java/com/example/mutsideout_mju/service/UserService.java
Labels: enhancement

#26 Hotfix/#25 설문 질문 전체 조회 API 변경
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/controller/SurveyController.java
Labels: bug

#28 Feature/#27 대상 그룹 확인용 컨트롤러 추가
  src/main/java/com/example/mutsideout_mju/controller/HealthController.java
Labels: enhancement

#30 Hotfix/#29 설문조사를 진행했던 사용자 검증 로직 추가
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/controller/SurveyController.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/UserSurveyRepository.java
  src/main/java/com/example/mutsideout_mju/service/SurveyService.java
Labels: bug

#32 Feature/#31 CORS 설정 추가
  src/main/java/com/example/mutsideout_mju/config/CorsConfig.java
Labels: enhancement

#36 Feature/#35 코드 정렬 및 필요없는 어노테이션 삭제
  src/main/java/com/example/mutsideout_mju/config/CorsConfig.java
  src/main/java/com/example/mutsideout_mju/controller/DiaryController.java
  src/main/java/com/example/mutsideout_mju/controller/SurveyController.java
  src/main/java/com/example/mutsideout_mju/dto/request/PaginationDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/auth/LoginDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/auth/SignupDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/PaginationData.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/PlannerListResponseData.java
  src/main/java/com/example/mutsideout_mju/service/DiaryService.java
Labels: enhancement

#38 Feature/#37 CI/CD 적용
  .github/workflows/gradle.yml
Labels: enhancement

#34 Feature/#33 planner api error
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/CompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/GroupedCompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/PlannerListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/PlannerResponseData.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/service/PlannerService.java
Labels: bug

#40 Fix/#39 DiaryResponseData 날짜 변환 수정
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseData.java
Labels: bug

#42 Hotfix/#41 CORS 설정 로직 변경
  src/main/java/com/example/mutsideout_mju/config/CorsConfig.java
Labels: bug

#44 Feature/#43 설문조사 질문 전체 조회 시 문항 번호 오름차순 정렬로 변경
  src/main/java/com/example/mutsideout_mju/service/SurveyService.java
Labels: enhancement

#23 Feature/#22 실시간 집중 세션 API 개발
  src/main/java/com/example/mutsideout_mju/controller/RoomController.java
  src/main/java/com/example/mutsideout_mju/dto/request/room/CreateRoomDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/room/UpdateRoomDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/diary/DiaryResponseDto.java
  src/main/java/com/example/mutsideout_mju/dto/response/room/RoomListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/room/RoomResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/room/RoomResponseDto.java
  src/main/java/com/example/mutsideout_mju/entity/Room.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/RoomRepository.java
  src/main/java/com/example/mutsideout_mju/service/DiaryService.java
  src/main/java/com/example/mutsideout_mju/service/RoomService.java
Labels: enhancement

#46 Feature/#45 사용자 등급 가져오기 API 개발
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/controller/UserController.java
  src/main/java/com/example/mutsideout_mju/dto/response/user/UserGradeResponseDto.java
  src/main/java/com/example/mutsideout_mju/service/UserService.java
Labels: enhancement

#50 Feature/#49 planner sorting
  src/main/java/com/example/mutsideout_mju/controller/PlannerController.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/CompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/CompletedPlannerResponseForClient.java
  src/main/java/com/example/mutsideout_mju/dto/response/planner/GroupedCompletedPlannerResponse.java
  src/main/java/com/example/mutsideout_mju/service/PlannerService.java
Labels: bug

#52 Feature/#51 회원가입 시 자동 로그인 기능 추가
  src/main/java/com/example/mutsideout_mju/controller/AuthController.java
  src/main/java/com/example/mutsideout_mju/service/AuthService.java
Labels: enhancement

#54 Feature/#53 delete planner
  src/main/java/com/example/mutsideout_mju/controller/PlannerController.java
  src/main/java/com/example/mutsideout_mju/exception/ForbiddenException.java
  src/main/java/com/example/mutsideout_mju/service/PlannerService.java
Labels: enhancement

#59 Feature/#58 회원 정보 수정 및 탈퇴 기능
  src/main/java/com/example/mutsideout_mju/controller/UserController.java
  src/main/java/com/example/mutsideout_mju/dto/request/user/DeleteUserDto.java
  src/main/java/com/example/mutsideout_mju/dto/request/user/UpdateUserDto.java
  src/main/java/com/example/mutsideout_mju/entity/User.java
  src/main/java/com/example/mutsideout_mju/service/UserService.java
Labels: enhancement

#63 Feature/#62 생성한 지 24시간이 지난 집중 세션 방 삭제 로직 최적화
  src/main/java/com/example/mutsideout_mju/repository/RoomRepository.java
  src/main/java/com/example/mutsideout_mju/service/RoomService.java
Labels: refactor

#68 Feature/#65 S3 설정 추가
  build.gradle
  src/main/java/com/example/mutsideout_mju/config/S3Config.java
  src/main/java/com/example/mutsideout_mju/dto/response/room/RoomListResponseData.java
  src/main/java/com/example/mutsideout_mju/dto/response/room/RoomResponseDto.java
  src/main/java/com/example/mutsideout_mju/service/RoomService.java
  src/main/java/com/example/mutsideout_mju/util/S3Service.java
Labels: enhancement

#67 Feature/#66 refreshtoken 추가
  src/main/java/com/example/mutsideout_mju/authentication/JwtTokenProvider.java
  src/main/java/com/example/mutsideout_mju/config/AuthenticationConfig.java
  src/main/java/com/example/mutsideout_mju/controller/AuthController.java
  src/main/java/com/example/mutsideout_mju/dto/response/token/TokenResponseDto.java
  src/main/java/com/example/mutsideout_mju/entity/RefreshToken.java
  src/main/java/com/example/mutsideout_mju/exception/errorCode/ErrorCode.java
  src/main/java/com/example/mutsideout_mju/repository/RefreshTokenRepository.java
  src/main/java/com/example/mutsideout_mju/service/AuthService.java
Labels: enhancement

#76 Feature/#71 설문조사 응답을 이용한 유저 등급 계산 로직 리팩토링
  src/main/java/com/example/mutsideout_mju/dto/response/user/UserGradeResponseDto.java
  src/main/java/com/example/mutsideout_mju/repository/planner/CustomPlannerRepository.java
  src/main/java/com/example/mutsideout_mju/repository/planner/CustomPlannerRepositoryImpl.java
  src/main/java/com/example/mutsideout_mju/repository/planner/PlannerRepository.java
  src/main/java/com/example/mutsideout_mju/repository/usersurvey/CustomUserSurveyRepository.java
  src/main/java/com/example/mutsideout_mju/repository/usersurvey/CustomUserSurveyRepositoryImpl.java
  src/main/java/com/example/mutsideout_mju/repository/usersurvey/UserSurveyRepository.java
  src/main/java/com/example/mutsideout_mju/service/PlannerService.java
  src/main/java/com/example/mutsideout_mju/service/SurveyService.java
  src/main/java/com/example/mutsideout_mju/service/UserService.java
Labels: enhancement, refactor
